const colors = {
  light: {
    text: "#1a1a2e",
    tint: "#7c4dbd",
    background: "#f7f5f0",
    foreground: "#1a1a2e",
    card: "#ffffff",
    cardForeground: "#1a1a2e",
    primary: "#7c4dbd",
    primaryForeground: "#ffffff",
    secondary: "#e8e0f5",
    secondaryForeground: "#1a1a2e",
    muted: "#ede9f5",
    mutedForeground: "#8a8099",
    accent: "#c8a96e",
    accentForeground: "#1a1a2e",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2ddf0",
    input: "#e2ddf0",
    gold: "#c8a96e",
    navy: "#1a1a2e",
    purple: "#7c4dbd",
    lightPurple: "#9b6de0",
  },
  dark: {
    text: "#f0edf8",
    tint: "#9b6de0",
    background: "#0f0d1a",
    foreground: "#f0edf8",
    card: "#1e1a30",
    cardForeground: "#f0edf8",
    primary: "#9b6de0",
    primaryForeground: "#ffffff",
    secondary: "#2a2240",
    secondaryForeground: "#f0edf8",
    muted: "#2a2240",
    mutedForeground: "#9b8fc0",
    accent: "#c8a96e",
    accentForeground: "#1a1a2e",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2e2650",
    input: "#2e2650",
    gold: "#c8a96e",
    navy: "#0f0d1a",
    purple: "#9b6de0",
    lightPurple: "#b588f5",
  },
  radius: 16,
};

export default colors;
